print("Responda o seguinte relatório")
print("###############################")
nome = (input("Escreva seu nome:"))
cpf = (input("Escreva seu CPF:"))
endereco = input("Escreva seu endereço:")
idade = input("Escreva sua idade:" )
altura =  input("Escreva sua altura:")
telefone = input("Escreva seu telefone:")
print("Nome:", nome)
print("CPF:", cpf)
print("Endereço:", endereco)
print("Idade:", idade)
print("Altura:",altura)
print("Telefone",telefone)
